# Generated by Django 3.0.8 on 2020-09-05 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indv', '0003_indvtask_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indvtask',
            name='prog',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='progressmodel',
            name='progress',
            field=models.IntegerField(default=0),
        ),
    ]
