# Generated by Django 3.0.5 on 2020-09-04 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TeamModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('members', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=40)),
            ],
            options={
                'verbose_name_plural': 'Teams',
            },
        ),
        migrations.CreateModel(
            name='GroupTasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=288)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='group.TeamModel')),
            ],
            options={
                'verbose_name_plural': 'Group_Tasks',
            },
        ),
    ]
